package-lock.json
package.json

Add missing dependencies

---

Dockerfile
README.md

Adds a working dockerfile to generate the MySQL database as well as instructions on how to set it up on the the readme.

Add dockerfile and environment documentation

---

.editorconfig

Add .editorconfig file to enforce coding style

---

package-lock.json
package.json

Should compile now. Tests will fail on purpose since frontend UI code isn't finished (from what it seems).

Fix dependency conflict

---

public/robots.txt

deleted robots.txt

---

browsebox-backend/controllers/user-controllers.js
src/App.js
src/pages/Edit/Edit.jsx
src/pages/Header/Header.jsx
src/pages/Home/Home.jsx
src/pages/Login/LoginForm.jsx
src/pages/Login/LoginModal.jsx

Functionally is the complete yet.

feat: user can edit their profile

---

browsebox-backend/controllers/sale-controllers.js
browsebox-backend/controllers/user-controllers.js
browsebox-backend/util/checkInput.js

Validates emails and usernames. 
No password input validation yet. Depends on how hashing will work.

Validation

---

browsebox-backend/database/browsebox.sql

User has school reference and items have default time set to now.

Updated fields

---

browsebox-backend/controllers/review-controllers.js
browsebox-backend/routes/review-routes.js
browsebox-backend/server.js

Tested get reviews. Returns right data.

Routed reviews

---

src/App.js
src/pages/Home/Home.jsx
src/pages/Item/Item.jsx

Basic structure of the item list.

feat: basic layout of cards.

---

src/Components/ItemComponents/CreateAd2.js
src/Components/ItemComponents/PictureBox.js

This component is 95% done.
Still need to test submit to database button
Some general text out of place
and some page formatting. (page too stretched)
There are alot of changes but all changes are collisions against my own stuff, so just push this ahead and have a lemonade.

This is an update to the CreateAd2.js and PictureBox.js.

---

src/App.js
src/Components/ItemComponents/CreateAd2.js
src/Components/ItemComponents/PictureBox.js
src/Components/ItemComponents/ViewAd.js
src/Components/Testing Compnents/SimpleNav.js

This ads a ViewAd.js component. It just shows the Ad. 
There is something wrong with what the database wants and what i am sending so I have just included sample data for now to test.
This is the second update. Not sure if they need to be merged with master in order.

Starting work opn the view add component

---

package-lock.json
package.json
src/App.js
src/Components/ItemComponents/CreateAd2.js
src/Components/ItemComponents/Navbar.js
src/Components/ItemComponents/PictureBox.js
src/Components/ItemComponents/ViewAd.js
src/Components/Testing Compnents/SimpleNav.js

Put together a quick more permenant navbar

---

browsebox-backend/controllers/sale-controllers.js
browsebox-backend/database/browsebox.sql
browsebox-backend/database/populate.sql
browsebox-backend/routes/sale-routes.js

cat_id now in sale table. Category is found with and updated with cat_id.
To change a sale's category, do so through update sale.
select statements return category name via a join

MAJOR UPDATE: 1:n category:sale

---

src/Components/ItemComponents/AdList.js
src/Components/ItemComponents/Congratulations.js
src/Components/ItemComponents/CreateAd2.js
src/Components/ItemComponents/EditItemModal.js
src/Components/ItemComponents/Navbar.js
src/Components/ItemComponents/ShowAds.js

- Finish the CreateAd2.js (Also updating for changes from the backend Major update)
- Finish the List Item component
- Finish the edit item component
- Finish the delete item component
These pages may need to be revisited to update ui and incorperate into rest of site. example get an actual userid set into the page for live traversal.

This is a fairly robust update it cover:

---

browsebox-backend/controllers/user-controllers.js

Server was stopping, as  no user was found to match the local storage ID

Only return user data if user is found

---

package-lock.json
package.json
src/pages/Home/Home.jsx

Buttoncreated

---

browsebox-backend/controllers/user-controllers.js

only the id field and one other is needed for updating a user

optional fields for user update

---

package-lock.json
src/App.js
src/pages/Edit/EditForm.jsx
src/pages/Edit/EditModal.jsx
src/pages/Header/Header.jsx
src/pages/Signup/SignupForm.jsx

moved edit to modal and added school field

---

browsebox-backend/controllers/chatControllers.js
browsebox-backend/database/browsebox.sql
browsebox-backend/models/chatModels.js
browsebox-backend/routes/chatRoutes.js
browsebox-backend/socketserver.js
src/App.js
src/Components/ChatComponents/ChatLoading.js
src/Components/ChatComponents/ChatLogics.js
src/Components/ChatComponents/ChatProvider.js
src/Components/ChatComponents/Chatbox.js
src/Components/ChatComponents/Chatpage.js
src/Components/ChatComponents/MyChats.js
src/Components/ChatComponents/SingleChat.js
src/Components/ChatComponents/styles.css

Add chat implementation

---

browsebox-backend/database/browsebox.sql

when user or sale is deleted, remove all references to it.

Added cascade

---

browsebox-backend/controllers/favorites-controller.js
browsebox-backend/routes/favorite-routes.js
browsebox-backend/server.js
src/Components/ItemComponents/FavoriteList.js
src/Components/Testing Compnents/ChatLoading.js
src/pages/Item/Item.jsx

Reverts BrowseBox/browsebox-web#108

Revert "Something wrong"

---

browsebox-backend/controllers/favorites-controller.js
browsebox-backend/routes/favorite-routes.js
browsebox-backend/server.js
src/pages/Item/Item.jsx

Switched from callbacks to promises.
Hooked up routing.
Issues: all items automatedly favourited, response to items already favourited is not working

Got favouriting mostly working

---

browsebox-backend/controllers/favorites-controller.js

Will allow the front end to continue as normal.

Items already favourited will return 200

---

src/pages/Home/Home.jsx
src/pages/Item/Item.jsx

cards now wrap
